Library/v2.6/src/Entity/Catalogue.php
<?php

namespace App\Entity;

use App\Repository\CatalogueRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CatalogueRepository::class)
 */
class Catalogue
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=150,unique=true)
     */
    private $mot_cle;

    /**
     * @ORM\OneToMany(targetEntity=Rubrique::class, mappedBy="catalogue", orphanRemoval=true)
     */
    private $rubrique;

    public function __construct()
    {
        $this->rubrique = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMotCle(): ?string
    {
        return $this->mot_cle;
    }

    public function setMotCle(string $mot_cle): self
    {
        $this->mot_cle = $mot_cle;

        return $this;
    }

    /**
     * @return Collection|Rubrique[]
     */
    public function getRubrique(): Collection
    {
        return $this->rubrique;
    }

    public function addRubrique(Rubrique $rubrique): self
    {
        if (!$this->rubrique->contains($rubrique)) {
            $this->rubrique[] = $rubrique;
            $rubrique->setCatalogue($this);
        }

        return $this;
    }

    public function removeRubrique(Rubrique $rubrique): self
    {
        if ($this->rubrique->contains($rubrique)) {
            $this->rubrique->removeElement($rubrique);
            // set the owning side to null (unless already changed)
            if ($rubrique->getCatalogue() === $this) {
                $rubrique->setCatalogue(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return $this->mot_cle;
    }
}

Library/v2.6/src/Entity/Exemplaire.php
<?php

namespace App\Entity;

use App\Repository\ExemplaireRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ExemplaireRepository::class)
 */
class Exemplaire
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $prix_unitaire;

    /**
     * @ORM\ManyToOne(targetEntity=Livre::class, inversedBy="exemplaires")
     * @ORM\JoinColumn(nullable=false)
     */
    private $livre;

    /**
     * @ORM\ManyToOne(targetEntity=Editeur::class, inversedBy="exemplaire")
     * @ORM\JoinColumn(nullable=false)
     */
    private $editeur;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPrixUnitaire(): ?float
    {
        return $this->prix_unitaire;
    }

    public function setPrixUnitaire(?float $prix_unitaire): self
    {
        $this->prix_unitaire = $prix_unitaire;

        return $this;
    }

    public function getLivre(): ?Livre
    {
        return $this->livre;
    }

    public function setLivre(?Livre $livre): self
    {
        $this->livre = $livre;

        return $this;
    }

    public function getEditeur(): ?Editeur
    {
        return $this->editeur;
    }

    public function setEditeur(?Editeur $editeur): self
    {
        $this->editeur = $editeur;

        return $this;
    }

}

Library/v2.6/src/Entity/LigneCommande.php
<?php

namespace App\Entity;

use App\Repository\LigneCommandeRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=LigneCommandeRepository::class)
 */
class LigneCommande
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $quantite;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $pourcentage_remise;

    public function __construct($quantite,$exemplaire)
    {
        $this->quantite=$quantite;
        $this->exemplaire=$exemplaire;
    }

    /**
     * @ORM\ManyToOne(targetEntity=Commande::class, inversedBy="lignecommande")
     * @ORM\JoinColumn(nullable=false)
     */
    private $commande;

    /**
     * @ORM\ManyToOne(targetEntity=Exemplaire::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $exemplaire;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getQuantite(): ?int
    {
        return $this->quantite;
    }

    public function setQuantite(int $quantite): self
    {
        $this->quantite = $quantite;

        return $this;
    }

    public function getPourcentageRemise(): ?int
    {
        return $this->pourcentage_remise;
    }

    public function setPourcentageRemise(?int $pourcentage_remise): self
    {
        $this->pourcentage_remise = $pourcentage_remise;

        return $this;
    }

    public function getCommande(): ?Commande
    {
        return $this->commande;
    }

    public function setCommande(?Commande $commande): self
    {
        $this->commande = $commande;

        return $this;
    }

    public function getExemplaire(): ?Exemplaire
    {
        return $this->exemplaire;
    }

    public function setExemplaire(?Exemplaire $exemplaire): self
    {
        $this->exemplaire = $exemplaire;

        return $this;
    }

    public function __toString()
    {
        return $this->getExemplaire()->getLivre()->getTitre();
    }

    public function getSousTotal()
    {
        //return $this->quantite * $this->getLivre()->getPrix();
        // to complete
        return ($this->quantite) * $this->getExemplaire()->getPrixUnitaire();
    }

}

Library/v2.6/templates/user/accueil.html.twig
{% extends 'base.html.twig' %}

{% block title %} Bambara Library {% endblock %}

{% block body %}
    <header>

        <!--barre de navigation-->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand"></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <div class="navbar-nav  mt-2 mt-lg-0">
                    <a class="nav-link nav-item" href="#"><img src="https://img.icons8.com/nolan/64/e-learning-2.png"
                                                               alt="online book"/>E-Librairie</a>
                </div>
                <div id="search" class="mr-auto">
                    <form class="form-inline my-2 my-lg-0">
                        <input class="form-control mr-sm-2" type="search" placeholder="Rechercher un livre, un auteur"
                               aria-label="Search">
                        <button type="submit"><i class="fas fa-search"></i></button>
                    </form>
                </div>
                <div class="navbar-nav form-inline my-2 my-lg-0">
                    <a class="nav-item nav-link" href="connexion"><img
                                src="https://img.icons8.com/nolan/25/user-folder.png"/>Compte connexion</a>
                    <a class="nav-link nav-item" href="panier"><img
                                src="https://img.icons8.com/nolan/25/add-to-basket.png"/>Panier</a>

                    <ul class="submenu menu vertical" data-submenu >
                        <table class="tabPanier">
                            <thead>
                            <tr>
                                <th>Livres</th>
                                <th>Quantité</th>
                                <th>Sous total</th>
                                <th>Actions</th>
                            </tr>
                            </thead>
                            <tbody>
                                {% for lc in lignesCmds %}
                                    <tr>
                                        <td>{{ lc.ligne_cmd }}</td>
                                        <td class="align-center"> {{ lc.ligne_cmd.quantite }} </td>
                                        <td class="align-right">
                                            <strong>{{ lc.ligne_cmd.sousTotal }} €</strong>
                                        </td>
                                        <td class="text-right">
                                            <a class="panierActionSupprimer" href="{{ path('panier_supprimer',{id:lc.ligne_cmd.exemplaire.id}) }}">
                                                <strong><i class="fas fa-trash-alt fa-lg"></i> </strong>
                                            </a>
                                        </td>
                                    </tr>
                                {% else %}
                                    <tr>
                                        <td colspan="4">Le panier est vide</td>
                                    </tr>
                                {% endfor %}

                                {% if total > 0 %}

                                    <tr class="total">
                                        <td colspan="2" class="text-right"><strong>TOTAL</strong></td>
                                        <td class="text-right primary"><strong>{{ total }}</strong></td>
                                        <td class="text-right primary"></td>
                                    </tr>
                                {% endif %}
                            </tbody>
                        </table>
                    </ul>
                </div>
            </div>
        </nav>
        <!--fin de la barre nav-->
    </header>

    <body>
    <div class="row">
        <div class="col dropdown">
            <a class="btn btn-secondary btn-block">
                CATALOGUES
            </a>
        </div>

        <div class="w-100"></div>

        {% for cat in catalogue|sort %}
            <div class="col dropdown">
                <div class="dropdown">
                    <button class="dropdown-item" href="#">{{ cat.motCle }} </button>
                    <div class="dropdown-content">
                        {% for rub in cat.rubrique |sort %}  <!-- Pour chaque catégorie on affiche toutes ses rubriques -->
                            <a href="#" target="_blank">{{ rub.classement }}</a> <!-- path('librairie_rubrique' -->
                        {% endfor %}
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    <hr>
    <div class="col">
        <div id="carousel" class="carousel slide" data-ride="carousel" data-interval="13000">
            <div class="carousel-inner">
                <!--
                <div class="carousel-item active">
                    <img class="d-block w-100 " src="../../img/carImg1.jpg" alt="First slide">
                </div>
                -->
                <div class="carousel-item active">
                    <img class="d-block w-100 " src="../../img/carImg2.jpg" alt="Second slide">
                </div>
                <div class="carousel-item">
                    <img class="d-block w-100 " src="../../img/carImg4.jpg" alt="Third slide">
                </div>
            </div>
        </div>
    </div>
    <hr>

    <div class="">
        <h2>Sélection du mois</h2>

        <div class="row">
            {% for exemplaire in exemplaires|sort %}

                <div id="selection" class="col-sm-3 col">  <!-- d-block can be useful here-->
                    <hr>
                    <h4>{{ exemplaire.livre.theme }}</h4>
                    <img src="{{ 'img/couvertureLivre/' }}{{ exemplaire.livre.imageName }}" alt="book image">
                    <blockquote>{{ exemplaire.livre.resumer }}</blockquote>
                    <a href="{{ path('panier_ajouter',{id:exemplaire.id}) }}"><i class="fas fa-shopping-cart"
                                                                            style="font-size: 1.5rem"></i> </a>
                    <a style="font-size: 1.5rem">{{ exemplaire.prixUnitaire }}€</a>
                </div>
            {% endfor %}
        </div>

    </div>

    </body>
    <hr>
    <footer id="footerpad">
        <div class="container">
            <div class="row">
                <div class="col-sm">
                    <h6>Rejoignez-nous sur</h6> <br>
                    <img src="https://img.icons8.com/nolan/25/facebook.png" alt="facebook"/>
                    <img src="https://img.icons8.com/nolan/25/pinterest.png" alt="pinterest"/>
                    <img src="https://img.icons8.com/nolan/25/instagram-new.png" alt="instagram"/>
                </div>

                <div class="col-sm">
                    <h6>Contact</h6> <br>
                    <a href="https://www.google.fr/maps/dir//92230+Gennevilliers/@48.9326635,2.230054,12z/data=!3m1!4b1!4m9!4m8!1m0!1m5!1m1!1s0x47e66f56b7677b3d:0x1c0b82c6e1d88050!2m2!1d2.3000941!2d48.9326847!3e3">
                        Adresse: 9B rue de la Sablière<br>92230 Gennevilliers </a> <br>
                    <a>Ligne 13 </a><br>
                    <a>RER C</a><br>
                    <a>Bus 177, 138, 366</a><br>
                </div>

                <div class="col-sm">
                    <h6>Besoin d'aide </h6><br>
                    <a href="https://translate.google.fr/?hl=fr#view=home&op=translate&sl=fr&tl=en">Traduction de la
                        page</a><br>
                    <a href="#">Suivi de commande</a><br>
                    <a href="#">Livraison frais de port</a><br>
                    <a href="https://pouruneautreeconomie.fr/moyen-de-paiement-en-ligne/">Paiement sécurisé</a><br>
                    <a href="#">Nous Contacter</a><br>
                </div>
            </div>
            <hr>
            <p class="copyright text-center">Copyright &copy; 2020 E-Librairie</p>
        </div>
    </footer>
{% endblock %}

Library/v2.6/templates/user/compte_connexion_actif.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    <header>
        <!--barre de navigation-->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" ></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarNav">

                <div class="navbar-nav mr-auto mt-2 mt-lg-0">
                    <a class="nav-link nav-item" href="/"><img src="https://img.icons8.com/nolan/64/e-learning-2.png"/>E-Librairie</a>
                </div>

                <div>
                    <form class="form-inline my-2 my-lg-0">
                        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">

                        <button type="submit"> <img src="https://img.icons8.com/nolan/25/google-web-search.png"/></button>
                    </form>
                </div>

                <div class="navbar-nav form-inline my-2 my-lg-0">

                    <a class="nav-item nav-link" href="connexion"><img src="https://img.icons8.com/nolan/25/user-folder.png"/>Compte connexion</a>

                    <a class="nav-link nav-item" href="panier"><img src="https://img.icons8.com/nolan/25/add-to-basket.png"/>Panier</a>
                </div>
            </div>
        </nav>
        <!--fin de la barre nav-->
    </header>

    <hr>

    <footer id="footerpad">
        <div class="container">
            <div class="row">

                <div class="col-sm">
                    <h6>Rjoignez-nous sur</h6> <br>
                    <img src="https://img.icons8.com/nolan/25/facebook.png"/><img src="https://img.icons8.com/nolan/25/pinterest.png"/><img src="https://img.icons8.com/nolan/25/instagram-new.png"/>
                </div>

                <div class="col-sm">
                    <h6>Contact</h6> <br>
                    <a href="https://www.google.fr/maps/dir//92230+Gennevilliers/@48.9326635,2.230054,12z/data=!3m1!4b1!4m9!4m8!1m0!1m5!1m1!1s0x47e66f56b7677b3d:0x1c0b82c6e1d88050!2m2!1d2.3000941!2d48.9326847!3e3">adresse : 92230 Gennevilliers </a> <br>
                    <a>Ligne 13 </a><br>
                    <a>RER C</a><br>
                    <a>Bus 177, 138, 366</a><br>
                </div>

                <div class="col-sm">
                    <h6>Besoin d'aide </h6><br>
                    <a href="https://translate.google.fr/?hl=fr#view=home&op=translate&sl=fr&tl=en">traduction de page</a><br>
                    <a href="#">suivi de commande</a><br>
                    <a href="#">livraison frais de port</a><br>
                    <a href="https://pouruneautreeconomie.fr/moyen-de-paiement-en-ligne/">Paiement sécurise</a><br>
                    <a href="#">Nous Contacter</a><br>

                </div>
            </div>
            <p class="copyright text-center">Copyright &copy; Librairie 2020</p>
        </div>

    </footer>

{% endblock %}

{% block title %}

{% endblock %}

Library/v2.6/templates/user/connexion.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    <header>
        <!--barre de navigation-->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" ></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarNav">

                <div class="navbar-nav mr-auto mt-2 mt-lg-0">
                    <a class="nav-link nav-item" href="/"><img src="https://img.icons8.com/nolan/64/e-learning-2.png"/>E-Librairie</a>
                </div>

                <div>
                    <form class="form-inline my-2 my-lg-0">
                        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">

                        <button type="submit"> <img src="https://img.icons8.com/nolan/25/google-web-search.png"/></button>
                    </form>
                </div>

                <div class="navbar-nav form-inline my-2 my-lg-0">

                    <a class="nav-item nav-link" href="connexion"><img src="https://img.icons8.com/nolan/25/user-folder.png"/>Compte connexion</a>

                    <a class="nav-link nav-item" href="panier"><img src="https://img.icons8.com/nolan/25/add-to-basket.png"/>Panier</a>
                </div>
            </div>
        </nav>
        <!--fin de la barre nav-->
    </header>

    <div class="row">
    <div class="col-8"><br>
        <h5>Nouveau Client</h5>
        <form>
            <input type="radio" id="male" name="gender" value="male">
            <label for="male">Monsieur</label>
            <input type="radio" id="female" name="gender" value="female">
            <label for="female">Madame</label><br>
                <div class="row">
                    <div class="col">
                        <input type="text" class="form-control" placeholder="Votre prenom">
                    </div>
                    <div class="col">
                        <input type="text" class="form-control" placeholder="Votre nom">
                    </div>
                </div> <br>

                <div class="row">
                    <div class="col">
                        <input type="email" class="form-control" placeholder="Votre email">
                    </div>
                    <div class="col">
                        <input type="password" class="form-control" placeholder="Mot de passe">
                    </div>
                </div> <br>

            <button type="submit" class="btn btn-primary" href="compte_connexion_actif">Créer votre compte</button>

        </form>
    </div>
    <div class="col-4"><br>
        <h5>Deja Client</h5>
        <h6>Identifiez-vous</h6>
        <form>
            <div class="form-group">
                <input type="email" class="form-control" placeholder="Votre email">
            </div>
            <div class="form-group">
                <input type="password" class="form-control" placeholder="Mot de passe">
            </div>

            <button type="submit" class="btn btn-primary" href="compte_connexion_actif">Me connecter</button>
        </form>
    </div>
</div>

<hr>
    <footer id="footerpad">
        <div class="container">
            <div class="row">

                <div class="col-sm">
                    <h6>Rjoignez-nous sur</h6> <br>
                    <img src="https://img.icons8.com/nolan/25/facebook.png"/><img src="https://img.icons8.com/nolan/25/pinterest.png"/><img src="https://img.icons8.com/nolan/25/instagram-new.png"/>
                </div>

                <div class="col-sm">
                    <h6>Contact</h6> <br>
                    <a href="https://www.google.fr/maps/dir//92230+Gennevilliers/@48.9326635,2.230054,12z/data=!3m1!4b1!4m9!4m8!1m0!1m5!1m1!1s0x47e66f56b7677b3d:0x1c0b82c6e1d88050!2m2!1d2.3000941!2d48.9326847!3e3">adresse : 92230 Gennevilliers </a> <br>
                    <a>Ligne 13 </a><br>
                    <a>RER C</a><br>
                    <a>Bus 177, 138, 366</a><br>
                </div>

                <div class="col-sm">
                    <h6>Besoin d'aide </h6><br>
                    <a href="https://translate.google.fr/?hl=fr#view=home&op=translate&sl=fr&tl=en">traduction de page</a><br>
                    <a href="#">suivi de commande</a><br>
                    <a href="#">livraison frais de port</a><br>
                    <a href="https://pouruneautreeconomie.fr/moyen-de-paiement-en-ligne/">Paiement sécurise</a><br>
                    <a href="#">Nous Contacter</a><br>

                </div>
            </div>
            <p class="copyright text-center">Copyright &copy; Librairie 2020</p>
        </div>

    </footer>
{% endblock %}

{% block title %}

{% endblock %}

Library/v2.6/templates/user/livre.html.twig
{% extends 'base.html.twig' %}

{% block title %}
{% endblock %}

{% block body %}

    <header>
        <!--barre de navigation-->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand"></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <div class="navbar-nav  mt-2 mt-lg-0">
                    <a class="nav-link nav-item" href="#"><img src="https://img.icons8.com/nolan/64/e-learning-2.png"
                                                               alt="online book"/>E-Librairie</a>
                </div>
                <div id="search" class="mr-auto">
                    <form class="form-inline my-2 my-lg-0">
                        <input class="form-control mr-sm-2" type="search" placeholder="Rechercher un livre" aria-label="Search">
                        <button type="submit"><i class="fas fa-search"></i></button>
                    </form>
                </div>
                <div class="navbar-nav form-inline my-2 my-lg-0">
                    <a class="nav-item nav-link" href="connexion"><img
                                src="https://img.icons8.com/nolan/25/user-folder.png"/>Log in / Register</a>
                    <a class="nav-link nav-item" href="panier"><img
                                src="https://img.icons8.com/nolan/25/add-to-basket.png"/>Panier</a>
                </div>
            </div>
        </nav>
        <!--fin de la barre nav-->
    </header>

    <!--
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" ></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarNav">

                <div class="navbar-nav mr-auto mt-2 mt-lg-0">
                    <a class="nav-link nav-item" href="/"><img src="https://img.icons8.com/nolan/64/e-learning-2.png"/>E-Librairie</a>
                </div>

                <div>
                    <form class="form-inline my-2 my-lg-0">
                        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">

                        <button type="submit"> <img src="https://img.icons8.com/nolan/25/google-web-search.png"/></button>
                    </form>
                </div>

                <div class="navbar-nav form-inline my-2 my-lg-0">

                    <a class="nav-item nav-link" href="connexion"><img src="https://img.icons8.com/nolan/25/user-folder.png"/>Compte connexion</a>

                    <a class="nav-link nav-item" href="panier"><img src="https://img.icons8.com/nolan/25/add-to-basket.png"/>Panier</a>
                </div>
            </div>
        </nav>
    -->

<hr>
    <footer id="footerpad">
        <div class="container">
            <div class="row">

                <div class="col-sm">
                    <h6>Rjoignez-nous sur</h6> <br>
                    <img src="https://img.icons8.com/nolan/25/facebook.png"/><img src="https://img.icons8.com/nolan/25/pinterest.png"/><img src="https://img.icons8.com/nolan/25/instagram-new.png"/>
                </div>

                <div class="col-sm">
                    <h6>Contact</h6> <br>
                    <a href="https://www.google.fr/maps/dir//92230+Gennevilliers/@48.9326635,2.230054,12z/data=!3m1!4b1!4m9!4m8!1m0!1m5!1m1!1s0x47e66f56b7677b3d:0x1c0b82c6e1d88050!2m2!1d2.3000941!2d48.9326847!3e3">adresse : 92230 Gennevilliers </a> <br>
                    <a>Ligne 13 </a><br>
                    <a>RER C</a><br>
                    <a>Bus 177, 138, 366</a><br>
                </div>

                <div class="col-sm">
                    <h6>Besoin d'aide </h6><br>
                    <a href="https://translate.google.fr/?hl=fr#view=home&op=translate&sl=fr&tl=en">traduction de page</a><br>
                    <a href="#">suivi de commande</a><br>
                    <a href="#">livraison frais de port</a><br>
                    <a href="https://pouruneautreeconomie.fr/moyen-de-paiement-en-ligne/">Paiement sécurise</a><br>
                    <a href="#">Nous Contacter</a><br>

                </div>
            </div>
            <p class="copyright text-center">Copyright &copy; Librairie 2020</p>
        </div>
    </footer>
{% endblock %}